# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-07-15 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_registrationtbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venues', models.CharField(max_length=50)),
            ],
        ),
    ]
