# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-07-15 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=50)),
                ('datetime', models.CharField(max_length=50)),
                ('venues', models.CharField(max_length=50)),
            ],
        ),
    ]
