# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-07-15 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_goalscore_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamA', models.CharField(max_length=50)),
                ('teamB', models.CharField(max_length=50)),
                ('datetime', models.CharField(max_length=50)),
                ('venues', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
