# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-07-15 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20200715_2057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fixture',
        ),
    ]
