# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-07-15 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_fixture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fixture',
        ),
    ]
